name: "health_analytics"
version: "1.0"
config-version: 2

profile: "health_analytics"

model-paths: ["models"]

models:
  health_analytics:
    staging:
      materialized: view
    marts:
      materialized: table
