health_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: warehouse_user
      password: warehouse_pass
      port: 5432
      dbname: warehouse
      schema: public
