version: 2

# Source name must not match dbname "warehouse" or dbt uses it as schema (warehouse.warehouse.table).
# Table is in schema "public" (warehouse/init.sql).
sources:
  - name: raw_warehouse
    schema: public
    tables:
      - name: health_life_expectancy
        columns:
          - name: country_code
            tests:
              - not_null
          - name: year
            tests:
              - not_null
          - name: life_expectancy
            tests:
              - not_null
